apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
  name: demo-devops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-devops
  template:
    metadata:
      labels:
        app: demo-devops
    spec:
      containers:
        - name: demo-devops
          image: jsenon/demo-devops:latest
          imagePullPolicy: Always
          resources:
            limits:
              memory: 256Mi
              cpu: "200m"
          command:
            - /demo-devops
          args:
            [
              "server",
              "--outputdir",
              "/datas",
              "--disabletrace",
            ]
          volumeMounts:
            - mountPath: /datas
              name: demo-devops-volume
      volumes:
        - name: demo-devops-volume
          emptyDir: {}
