---
kind: Service
apiVersion: v1
metadata:
  annotations:
    prometheus.io/scrape: "false"
    prometheus.io/port: "8080"
  labels:
    app: demo-devops
  name: demo-devops
spec:
  selector:
    app: demo-devops
  ports:
    - protocol: TCP
      name: http-8080
      port: 8080
      targetPort: 8080
